// @unocss-include
const config = [
  {
    icon: 'https://cdn-icons-png.flaticon.com/512/2548/2548881.png',
    title: '聊天🔥',
    id: 'chat',
    desc: '支持会话上下文理解能力的智能问答聊天机器人',
    url: './chat/index',
    className: 'from-pink-500 via-red-500 to-yellow-500',
  },
  {
    icon: 'https://cdn-icons-png.flaticon.com/128/726/726623.png',
    title: '邮件助手🔥',
    desc: '帮你生成客套话、富有创意和引人入胜的电子邮件内容的工具',
    url: './generic/index',
    id: 'email',
    className: 'from-purple-600 to-pink-600',
    pageConfig: {
      inputTitle: '请输入邮件内容',
      placeholder: 'eg: 邀请小明周末吃饭',
      val: '',
      prompt: 'Generate a business email in {{category}} that is friendly, but still professional and appropriate for the workplace.The topic is: ',
      category: {
        title: '选择语言',
        val: 'Simplified Chinese',
        options: [
          { value: 'UK English', text: '英语' },
          { value: 'Simplified Chinese', text: '中文' },
          { value: 'Japanese', text: '日语' },
          { value: 'Italiano', text: '意大利语' },
          { value: 'Español', text: '西班牙语' },
          { value: 'French', text: '法语' },
          { value: '한국어', text: '韩语' },
        ],
      },
    },
  },
  // {
  //   icon: 'https://cdn-icons-png.flaticon.com/512/3658/3658959.png',
  //   title: '电影推荐',
  //   desc: '一个为您的电子邮件生成富有创意和引人入胜的主题行的工具，帮助您获得更多的打开和点击！',
  //   url: './generic/index',
  //   id: 'movie',
  //   className: 'from-green-300 via-blue-500 to-purple-600',
  // },
  {
    icon: 'https://img.88icon.com/download/jpg/20200905/fbfdcc6d503f999641bec1d4b40869ca_512_512.jpg!88bg',
    title: '日周报生成🔥',
    desc: '输入工作内容，小助手帮你快速完成周报',
    url: './generic/index',
    id: 'weekly',
    className: 'from-purple-200 via-purple-400 to-purple-800',
    pageConfig: {
      inputTitle: '请输入日报内容',
      placeholder: 'eg: 完成了扫码登录功能，优化了UI',
      val: '',
      prompt: '围绕以下工作内容，帮我补充并写个工作的{{category}}，内容+列表的形式: ',
      category: {
        title: '选择类型',
        val: '日报',
        options: [
          { value: '日报', text: '日报' },
          { value: '周报', text: '周报' },
          { value: '月报', text: '月报' },
        ],
      },
    },
  },
  {
    icon: 'https://cos.codefe.top/images/xiaohongshu_icon.png',
    title: '小红书风格模拟器',
    desc: '输入你想发布的内容，帮你生成小红书的风格 ',
    url: './generic/index',
    id: 'xiaohongshu',
    className: 'from-purple-400 to-yellow-400',
    pageConfig: {
      inputTitle: '输入文案',
      placeholder: 'eg: 安利一款迪奥口红',
      val: '',
      prompt: '帮我扩展一下这段文字，起一个能吸引眼球的标题，内容润色成小红书的风格，每行开头都用不同的emoji: ',
    },
  },
  {
    icon: 'http://up.54fcnr.com/pic_source/04/40/00/044000bea092cdd4c5ed64d53d161730.gif',
    title: '哄女友小助手',
    desc: '请输入女朋友生气的原因，小助手为你生成一段道歉的话',
    url: './generic/index',
    id: 'apology',
    className: 'from-green-300 to-purple-400',
    pageConfig: {
      inputTitle: '请输入内容',
      placeholder: 'eg: 情人节没买礼物',
      val: '',
      prompt: '针对下面惹女朋友生气的原因，生成一段用于对女盆友道歉的文案，态度要表现的诚恳: ',
    },
  },
  {
    icon: 'https://cdn-icons-png.flaticon.com/512/2917/2917633.png',
    title: '食谱推荐',
    desc: '一种工具，可帮助您根据厨房中已有的食材查找食谱',
    url: './generic/index',
    id: 'recipe',
    className: 'from-fuchsia-500 via-red-600 to-orange-400',
    pageConfig: {
      inputTitle: '请输入食材',
      placeholder: 'eg: 土豆、胡萝卜',
      val: '',
      prompt: '针对下面这些食材，请帮我推荐一份合适的菜谱，并说出具体烹饪方法，风格是{{category}}: ',
      category: {
        title: '选择类型',
        val: '中餐',
        options: [
          { value: '中餐', text: '中餐' },
          { value: '西餐', text: '西餐' },
        ],
      },
    },
  },
  {
    icon: 'https://cos.codefe.top/images/roadblock.png',
    title: '施工中',
    desc: '敬请期待',
    url: './generic/index',
    id: 'recipe',
    className: 'bg-gray-400',
    status: 0,
  },
]
export default config
