/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by vite-plugin-uni-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Card: typeof import('./components/Card.vue')['default']
    MessageItem: typeof import('./components/MessageItem.vue')['default']
    MpHtml: typeof import('./components/mp-html/mp-html.vue')['default']
    Node: typeof import('./components/mp-html/node/node.vue')['default']
  }
}
